# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ubdb/v1/ubdb.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ubdb/v1/ubdb.proto\x12\x07ubdb.v1\"/\n\x15\x41\x64\x64\x42ucketEntryRequest\x12\x16\n\x06\x62ucket\x18\x01 \x01(\tR\x06\x62ucket\"\x18\n\x16\x41\x64\x64\x42ucketEntryResponse\"2\n\x18UpdateBucketEntryRequest\x12\x16\n\x06\x62ucket\x18\x01 \x01(\tR\x06\x62ucket\"\x1b\n\x19UpdateBucketEntryResponse\"2\n\x18\x44\x65leteBucketEntryRequest\x12\x16\n\x06\x62ucket\x18\x01 \x01(\tR\x06\x62ucket\"\x1b\n\x19\x44\x65leteBucketEntryResponse2\x98\x02\n\x0bUBDBService\x12Q\n\x0e\x41\x64\x64\x42ucketEntry\x12\x1e.ubdb.v1.AddBucketEntryRequest\x1a\x1f.ubdb.v1.AddBucketEntryResponse\x12Z\n\x11\x44\x65leteBucketEntry\x12!.ubdb.v1.DeleteBucketEntryRequest\x1a\".ubdb.v1.DeleteBucketEntryResponse\x12Z\n\x11UpdateBucketEntry\x12!.ubdb.v1.UpdateBucketEntryRequest\x1a\".ubdb.v1.UpdateBucketEntryResponseB\x89\x01\n\x0b\x63om.ubdb.v1B\tUbdbProtoP\x01Z2bits.linode.com/StorageTeam/ubns/gen/proto/ubdb/v1\xa2\x02\x03UXX\xaa\x02\x07Ubdb.V1\xca\x02\x07Ubdb\\V1\xe2\x02\x13Ubdb\\V1\\GPBMetadata\xea\x02\x08Ubdb::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ubdb.v1.ubdb_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.ubdb.v1B\tUbdbProtoP\001Z2bits.linode.com/StorageTeam/ubns/gen/proto/ubdb/v1\242\002\003UXX\252\002\007Ubdb.V1\312\002\007Ubdb\\V1\342\002\023Ubdb\\V1\\GPBMetadata\352\002\010Ubdb::V1'
  _globals['_ADDBUCKETENTRYREQUEST']._serialized_start=31
  _globals['_ADDBUCKETENTRYREQUEST']._serialized_end=78
  _globals['_ADDBUCKETENTRYRESPONSE']._serialized_start=80
  _globals['_ADDBUCKETENTRYRESPONSE']._serialized_end=104
  _globals['_UPDATEBUCKETENTRYREQUEST']._serialized_start=106
  _globals['_UPDATEBUCKETENTRYREQUEST']._serialized_end=156
  _globals['_UPDATEBUCKETENTRYRESPONSE']._serialized_start=158
  _globals['_UPDATEBUCKETENTRYRESPONSE']._serialized_end=185
  _globals['_DELETEBUCKETENTRYREQUEST']._serialized_start=187
  _globals['_DELETEBUCKETENTRYREQUEST']._serialized_end=237
  _globals['_DELETEBUCKETENTRYRESPONSE']._serialized_start=239
  _globals['_DELETEBUCKETENTRYRESPONSE']._serialized_end=266
  _globals['_UBDBSERVICE']._serialized_start=269
  _globals['_UBDBSERVICE']._serialized_end=549
# @@protoc_insertion_point(module_scope)
